language: rust

rust:
- stable
- beta
- nightly

script:
- cargo test --all
- git diff  # for proptest-regressions

matrix:
  include:
  - os: osx

  # TODO(#6): Run tests here instead of just building
  - name: cargo build -Z minimal-versions
    install:
    - rustup toolchain add nightly
    script:
    - cargo +nightly update -Z minimal-versions
    - cargo build --all

  - name: cargo fmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: cargo clippy
    install:
    - rustup component add clippy
    script:
    - cargo clippy --all --all-targets -- -D warnings

branches:
  only: [staging, trying, master]
