language: rust

rust:
- nightly-2019-02-06
- nightly
- beta
- stable

script:
- cargo test --all
- git diff

matrix:
  allow_failures:
  - rust: nightly

  include:
  - name: cargo test
    os: osx
    rust: stable

  # TODO(#6): Run tests here instead of just building
  - name: cargo build -Z minimal-versions
    script:
    - cargo update -Z minimal-versions
    - cargo build --all

  - name: cargo fmt
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: cargo clippy
    install:
    - rustup component add clippy
    script:
    - cargo clippy --all --all-targets -- -D warnings

branches:
  only: [staging, trying, master]
