[package]
authors = ["Wim Looman <wim@nemo157.com>"]
name = "cbor-diag"
version = "0.1.3"
description = """
A crate for parsing data encoded in [Concise Binary Object Representation
(CBOR)](https://cbor.io) (in any of raw binary, hex encoded (with comments) or
diagnostic notation) then printing it out in either annotated hex form or
diagnostic notation.
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/Nemo157/cbor-diag-rs"

[workspace]
members = ["cli"]

[dependencies]
hex = { version = "0.3.2", default-features = false }
nom = { version = "5.0.1", default-features = false, features = ["std"] }
half = { version = "1.3.0", default-features = false }
chrono = { version = "0.4.9", default-features = false }
base64 = { version = "0.10.1", default-features = false }
url = { version = "2.1.0", default-features = false }
num-rational = { version = "0.2.2", default-features = false, features = ["bigint"] }
num-bigint = { version = "0.2.3", default-features = false, features = ["std"] }
num-traits = { version = "0.2.8", default-features = false }
separator = { version = "0.4.0", default-features = false }
uuid = { version = "0.7.4", default-features = false }
bs58 = { version = "0.2.5", default-features = false }
pretty_assertions = { version = "0.6.1", default-features = false }

[dev-dependencies]
indoc = { version = "0.3.1", default-features = false }
proptest = { version = "0.9.0", default-features = false, features = ["std"] }
