[package]
name = "cbor-diag-cli"
version = "0.1.0"
authors = ["Wim Looman <wim.looman@kiwi.ki>"]
edition = "2018"

[[bin]]
name = "cbor-diag"
path = "src/main.rs"

[dependencies]
cbor-diag = { path = ".." }
paw = { version = "1.0.0", default-features = false }
structopt = { version = "0.3.0", default-features = false, features = ["paw", "color"] }
strum = { git = "https://github.com/Peternator7/strum", branch = "refactor", default-features = false, features = ["derive"] }
log = { version = "0.4.8", default-features = false }
pretty_env_logger = { version = "0.3.1", default-features = false }
