name: update

env:
  RUST_BACKTRACE: 1

jobs:
  dependencies:
    name: cargo update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.password ${{ secrets.MACHINE_USER_PAT }}
        git remote set-url origin https://github.com/Satelles157/cbor-diag-rs
        git fetch --unshallow -p origin
    - uses: hecrj/setup-rust-action@v1
    - id: update
      run: |
        LOG="$(cargo update 2>&1 | tail -n +2)"
        LOG="${LOG//'%'/'%25'}"
        LOG="${LOG//$'\n'/'%0A'}"
        LOG="${LOG//$'\r'/'%0D'}"
        echo "::set-output name=log::$LOG"
    - uses: actions-rs/cargo@v1
      with:
        command: update
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.MACHINE_USER_PAT }}
        request-to-parent: true
        commit-message: |
          Update dependencies
          
          ${{ steps.update.outputs.log }}
        committer: Satelles157 <satelles@nemo157.com>
        author: Satelles157 <satelles@nemo157.com>
        title: Update dependencies
        body: ${{ steps.update.outputs.log }}
        branch: update/dependencies

on:
  schedule:
  - cron: '20 14 * * 6'
